name: Check Sphinx external links
on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 0'  # once every Sunday at midnight ET
  workflow_dispatch:

jobs:
  check-external-links:
    name: Check for broken Sphinx external links
    runs-on: ubuntu-latest
    steps:
      - name: Cancel any previous incomplete runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Sphinx dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install .

      - name: Check Sphinx external links
        run: |
          cd docs  # run_doc_autogen assumes spec is found in ../spec/
          sphinx-build -b linkcheck ./source ./test_build
