name: Check Sphinx external links
on:
  push:
  schedule:
    - cron: '0 5 * * 0'  # once every Sunday at midnight ET
  workflow_dispatch:

jobs:
  check-external-links:
    name: Check for broken Sphinx external links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Sphinx dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install .

      - name: Check Sphinx external links
        run: |
          cd docs  # run_doc_autogen assumes spec is found in ../spec/
          sphinx-build -b linkcheck ./source ./test_build
