name: Run code coverage
on:
  push:
  workflow_dispatch:

jobs:
  run-coverage:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # TODO handle forks
    # run pipeline on either a push event or a PR event on a fork
    # if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:  # used by codecov-action
      OS: ${{ matrix.os }}
      PYTHON: '3.12'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Install package
        run: |
          python -m pip install -e .  # must install in editable mode for coverage to find sources
          python -m pip list

      - name: Run tests and generate coverage report
        run: |
          pytest --cov
          python -m coverage xml  # codecov uploader requires xml format
          python -m coverage report -m

      # TODO uncomment after setting up repo on codecov.io
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
